"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./service/store";
import { SessionProvider } from "next-auth/react";
// import '@/styles/globals.css'; 
import { Poppins } from '@next/font/google';

import { Epilogue } from '@next/font/google';

const epilogue = Epilogue({
  subsets: ['latin'],
  weight: ['400', '700'], 
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], 
});

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider >
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
    </SessionProvider>
  );
}